version: '3'
services:
  webserver:
    build:
      context: ..
      dockerfile: build/package/Dockerfile
    image: ksysctl/uruk
    container_name: uruk_webserver
    ports:
      - 8000:8000
    depends_on:
      - mysql
    restart: on-failure

  mysql:
    image: mysql
    container_name: uruk_mysql
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=${DATABASE_ROOT_PASSWORD}
      - MYSQL_DATABASE=${DATABASE_NAME}
      - MYSQL_USER=${DATABASE_USERNAME}
      - MYSQL_PASSWORD=${DATABASE_PASSWORD}
    cap_add:
      - SYS_NICE
    command: [
      'mysqld',
      '--character-set-server=utf8mb4',
      '--collation-server=utf8mb4_unicode_ci',
      '--explicit_defaults_for_timestamp'
    ]
    volumes:
      - ../sql/migrations:/docker-entrypoint-initdb.d:ro
      - ../sql/data:/var/lib/mysql:rw